channels:
        - conda-forge
        - rdkit
dependencies:
        - rdkit
        - ipython
        - ipywidgets
        - appmode
        - ipympl
        - numpy
        - openbabel=2.4.1
        - nglview
        - mplcursors
        - qgrid